# Generated by Django 3.0.6 on 2020-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_pricse', models.FloatField()),
                ('product_disc', models.CharField(max_length=500)),
                ('product_fsval', models.FloatField()),
                ('product_cval', models.FloatField()),
                ('product_thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
